version: "3.9"
services:
    postgres:
        image: postgres:14
        env_file:
            - .env
        environment:
            POSTGRES_USER: ${DB_USER}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
            POSTGRES_DB: ${DB_NAME}
        ports:
            - 5432:5432
        volumes:
            - pguserdata:/var/lib/postgresql/data

volumes:
    pguserdata: